[[operations]]
    Name = "Download from Git URL"
    id = "1"
    description = "Clone a game repository from a Git URL."
    script = "download_module_git"
    script_type = "internal"
[[operations.prompts]]
    Name = "url"
    type = "text"
    message = "Enter Git URL"

[[operations]]
    Name = "Download from Registry"
    id = "2"
    description = "Clone a game repository from the known registry list."
    script = "download_module_registry"
    script_type = "internal"
    [[operations.prompts]]
        Name = "url"
        type = "select"
        message = "Select module from registry"
        choices_provider = "registry_modules"
